import type { Metadata } from 'next'
import { HeaderOne, SuspendeButtons } from '@/components'
import '@/styles/sass/index.scss'
import { ThemeOne } from '@/layout'
import 'react-photo-view/dist/react-photo-view.css'
import { FooterOne } from '@/components/modules/footer'
import { Box } from '@mui/material'

export const metadata: Metadata = {
  title: 'Aventura en tu escuela',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
    <html lang='en'>
      <body>
        <ThemeOne>
          <HeaderOne />
          {children}
          <FooterOne />
        </ThemeOne>
        <SuspendeButtons />F
        <Box
          sx={{
            '& img': {
              position: 'fixed',
              bottom: '20px',
              left: '20px',
              width: '70px',
              height: '70px',
              color: 'white',
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
              borderRadius: '50%',
              cursor: 'pointer',
              transition: 'transform 0.3s ease'
            }
          }}
        >
          <a href="https://www.facebook.com/AventuraentuEscuela?mibextid=LQQJ4d" target='_blank'>
            <img src='https://img.icons8.com/?size=100&id=118497&format=png&color=000000' alt='whats-icon' />
          </a>
        </Box>
      </body>
    </html>
  )
}
